apiVersion: v1
kind: Service
metadata:
  name: t2s-nodejs-app
  namespace: default
spec:
  selector:
    app: t2s-nodejs-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
